// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Trivial function to prove the Rust-WASM-Dart pipeline works.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Deliberately trigger a panic to verify console_error_panic_hook works.
/// For testing/verification only.
void testPanic() => RustLib.instance.api.crateApiSimpleTestPanic();
